# Generated by Django 5.2.10 on 2026-01-14 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapturedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="captured_images/%Y/%m/%d/")),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("Bear", "Bear"),
                            ("Bision", "Bision"),
                            ("Elephant", "Elephant"),
                            ("Human", "Human"),
                            ("Leopord", "Leopord"),
                            ("Lion", "Lion"),
                            ("Tiger", "Tiger"),
                            ("Wild Boar", "Wild Boar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence score from YOLO model (0-1)"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_images",
                        to="api.device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Captured Image",
                "verbose_name_plural": "Captured Images",
                "ordering": ["-timestamp"],
            },
        ),
    ]
