# Generated by Django 5.2.10 on 2026-01-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_capturedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="home_lat",
            field=models.FloatField(blank=True, help_text="Home Latitude", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="home_lon",
            field=models.FloatField(blank=True, help_text="Home Longitude", null=True),
        ),
    ]
