# Generated by Django 5.2.10 on 2026-01-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_home_coordinates_to_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("public", "Public"), ("ranger", "Ranger")],
                default="public",
                max_length=10,
            ),
        ),
    ]
