# Generated by Django 5.2.10 on 2026-01-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_add_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="capturedimage",
            name="annotated_image",
            field=models.ImageField(
                blank=True,
                help_text="YOLO annotated image with bounding boxes",
                null=True,
                upload_to="annotated_images/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="capturedimage",
            name="image",
            field=models.ImageField(
                help_text="Original captured image",
                upload_to="captured_images/%Y/%m/%d/",
            ),
        ),
    ]
